### PR TITLE
Update 简体中文.txt

### PR DESCRIPTION
**Pull request by Jmh4008**
checked to #526#, unfinished.
need some time to finish it.

the translation problem mainly occur in the guide, which contains long sentence.

### CODE REVIEW

**Comment by Romenics** [comment]
Please let me know when you will be ready and I will apply this translation

**Comment by Jmh4008** [comment]
I think I should need a few days. I should work on #534# to the end.

**Comment by Jmh4008** [comment]
I think I have finished the simplified Chinese. I add words in () in case I make mistake. And I didn't translate those important sentences which are about building sever, and a few words that I haven't meet them in games so that I don't know what it means.

Before my work, the translation of simplified and tradition Chinese are the same except the typeface. So the translation problem of tradition Chinese still exist. But the translation work was good enough for playing.
And my work is just adjust the sentence of guide. 

But there is still some display problem in Chinese, I think it's because there is no space between the "#" and the first world in Chinese. So I will insect " " in them in the last update, if the problem get worse, then use the former update.

**Comment by Romenics** [comment]
Can you please clarify this "And when this is finally applied, please allow me to add some introduction about the current Chinese translation progress in Chinese. "
What exactly you want to do?

And thanks for help! I will send you direct access to repository.

**Comment by Jmh4008** [comment]
Oh, I want to tell Chinese steamer that, the current translation isn't perfect yet, but it's good enough to have a try on this game. I hope this information can be sent by you, the developer. I hoped some Chinese sentence can be added in updated news.

I want to add sentence in Chinese is that 
“目前简体中文版本经过国人完善，一般玩家可以通过教程无障碍地了解游戏。同时游戏进程中的绝大部分文本亦经过翻译和校对。希望能帮助到有兴趣的朋友。”

Which in English is that
 "The translation of simplify Chinese has been polished by Chinese. And we think common Chinese steamer can learn about this game easily with the guide. And most characters in game process are translated and proofread. We hope to help those interested in this game."

I hope to deliver this message because I said that the game's translation is annoying once on the steam page.
And I think it will be a eye-catcher when they see some Chinese letter in lines of English words.

**Comment by Romenics** [comment]
Understood. Good idea. We will add this text in the next update post which will be displayed only for Chinese users.

**Pull request merged**
